const { CHECK_POINT_FIELD_END, CHECK_POINT_FIELD_BOSS } = require('areas/field');
const { CHECK_POINT_FOREST_UPPER_START, CHECK_POINT_FOREST_UPPER_BOSS } = require('areas/forestUpper');
const { CHECK_POINT_FOREST_LOWER_START, CHECK_POINT_FOREST_LOWER_BOSS } = require('areas/forestLower');

const { CHECK_POINT_SKY_START, CHECK_POINT_SKY_BOSS } = require('areas/sky');
const { CHECK_POINT_CITY_START } = require('areas/city');
const { CHECK_POINT_RESTAURANT_START, CHECK_POINT_RESTAURANT_BOSS } = require('areas/restaurant');
const { CHECK_POINT_SEWER_START, CHECK_POINT_SEWER_BOSS } = require('areas/sewer');

const { CHECK_POINT_BEACH_START, CHECK_POINT_BEACH_BOSS } = require('areas/beach');
const { CHECK_POINT_CIRCUS_START, CHECK_POINT_CIRCUS_BOSS } = require('areas/circus');

const { CHECK_POINT_OCEAN_START } = require('areas/ocean');
const { CHECK_POINT_CASTLE_START, CHECK_POINT_CASTLE_BOSS } = require('areas/castle');

const checkPointArray = [
    CHECK_POINT_FIELD_END, CHECK_POINT_FIELD_BOSS,
    CHECK_POINT_FOREST_UPPER_START, CHECK_POINT_FOREST_UPPER_BOSS,
    CHECK_POINT_FOREST_LOWER_START, CHECK_POINT_FOREST_LOWER_BOSS,

    CHECK_POINT_SKY_START, CHECK_POINT_SKY_BOSS,
    CHECK_POINT_CITY_START,
    CHECK_POINT_RESTAURANT_START, CHECK_POINT_RESTAURANT_BOSS,
    CHECK_POINT_SEWER_START, CHECK_POINT_SEWER_BOSS,

    CHECK_POINT_BEACH_START, CHECK_POINT_BEACH_BOSS,
    CHECK_POINT_CIRCUS_START, CHECK_POINT_CIRCUS_BOSS,

    CHECK_POINT_OCEAN_START,
    CHECK_POINT_CASTLE_START, CHECK_POINT_CASTLE_BOSS,
];
window.checkPointArray = checkPointArray;

module.exports = {
    checkPointArray
};
