
module.exports = {
    WIDTH: 800, HEIGHT: 600, GAME_HEIGHT: 564,
    FRAME_LENGTH: 20, OFFSCREEN_PADDING: 40,
    ACCELERATION: 1, MAX_SPEED: 10, SHOT_COOLDOWN: 8, ATTACK_OFFSET: -4,
    ENEMY_COOLDOWN: 10, DEATH_COOLDOWN: 1000, SPAWN_COOLDOWN: 1000, SPAWN_INV_TIME: 2000,
    POINTS_FOR_POWERUP: 1000,

    ENEMY_FLY: 'fly',
    ENEMY_HORNET: 'hornet',
    ENEMY_FLYING_ANT: 'flyingAnt',
    ENEMY_FLYING_ANT_SOLDIER: 'flyingAntSoldier',
    ENEMY_MONK: 'monk',

    EFFECT_DAMAGE: 'damage', EFFECT_EXPLOSION: 'explosion', EFFECT_DUST: 'dust',
    LOOT_COIN: 'coin',
    LOOT_LIFE: 'life',
    LOOT_LADYBUG: 'ladybug',
    LOOT_SPEED: 'speed',
    LOOT_ATTACK_POWER: 'power',
    LOOT_ATTACK_SPEED: 'attackSpeed',
};
