
module.exports = {
    TEST_ITEMS: false,
    TEST_ENEMY: false,
    //TEST_ITEMS: ['tripleCombo', 'combo'],
    //TEST_ITEMS: ['normalLadybug','lightningLadybug','penetratingLadybug'],
    //TEST_ENEMY: 'brownSpider',

    WIDTH: 800, HEIGHT: 600, GAME_HEIGHT: 564, HUD_HEIGHT: 36,
    FRAME_LENGTH: 20, OFFSCREEN_PADDING: 40,
    ACCELERATION: 1, SHOT_COOLDOWN: 8, ATTACK_OFFSET: -4,
    ENEMY_COOLDOWN: 10, DEATH_COOLDOWN: 1000, SPAWN_COOLDOWN: 1000,

    HERO_BEE: 'bee', HERO_DRAGONFLY: 'dragonfly', HERO_MOTH: 'moth',
    MAX_ENERGY: 20,

    ENEMY_FLY: 'fly',
    ENEMY_HORNET: 'hornet',
    ENEMY_HORNET_SOLDIER: 'hornetSoldier',
    ENEMY_FLYING_ANT: 'flyingAnt',
    ENEMY_FLYING_ANT_SOLDIER: 'flyingAntSoldier',
    ENEMY_MONK: 'monk',
    ENEMY_CARGO_BEETLE: 'cargoBeetle',
    ENEMY_EXPLOSIVE_BEETLE: 'explosiveBeetle',
    ENEMY_LOCUST: 'locust',
    ENEMY_LOCUST_SOLDIER: 'locustSoldier',

    ATTACK_BLAST: 'blast', ATTACK_SLASH: 'slash', ATTACK_STAB: 'stab', ATTACK_BULLET: 'bullet',
    ATTACK_SPRAY_UP: 'sprayUp',
    ATTACK_SPRAY_RIGHT: 'sprayRight',
    ATTACK_SPRAY_DOWN: 'sprayDown',
    ATTACK_LASER: 'laser', ATTACK_ORB: 'orb',
    ATTACK_DEFEATED_ENEMY: 'defeatedEnemy', ATTACK_EXPLOSION: 'explosion',

    EFFECT_DAMAGE: 'damage', EFFECT_EXPLOSION: 'explosion', EFFECT_DUST: 'dust',
    EFFECT_DEAD_BEE: 'deadBee', EFFECT_SWITCH_BEE: 'switchBee',
    EFFECT_DEAD_DRAGONFLY: 'deadDragonfly', EFFECT_SWITCH_DRAGONFLY: 'switchDragonfly',
    EFFECT_DEAD_MOTH: 'deadMoth', EFFECT_SWITCH_MOTH: 'switchMoth',
    EFFECT_NEEDLE_FLIP: 'needleFlip',
    EFFECT_RATE_UP: 'rateUp', EFFECT_SIZE_UP: 'sizeUp', EFFECT_SPEED_UP: 'speedUp',
    EFFECT_DEFLECT_BULLET: 'deflect',
    LOOT_COIN: 'coin',
    LOOT_LIFE: 'life',
    LOOT_NORMAL_LADYBUG: 'normalLadybug',
    LOOT_LIGHTNING_LADYBUG: 'lightningLadybug',
    LOOT_PENETRATING_LADYBUG: 'penetratingLadybug',
    LOOT_SPEED: 'speed',
    LOOT_ATTACK_POWER: 'power',
    LOOT_ATTACK_SPEED: 'attackSpeed',
    LOOT_TRIPLE_SPEED: 'tripleSpeed',
    LOOT_TRIPLE_POWER: 'triplePower',
    LOOT_TRIPLE_RATE: 'tripleRate',
    LOOT_COMBO: 'combo',
    LOOT_TRIPLE_COMBO: 'tripleCombo',
    LOOT_PORTAL: 'portal',
    LOOT_HELMET: 'helmet',
};
