
module.exports = {
    WIDTH: 800, HEIGHT: 600, GAME_HEIGHT: 564,
    FRAME_LENGTH: 20, OFFSCREEN_PADDING: 40,
    ACCELERATION: 1, MAX_SPEED: 10, SHOT_COOLDOWN: 8,
    ENEMY_COOLDOWN: 10, DEATH_COOLDOWN: 1000, SPAWN_COOLDOWN: 1000, SPAWN_INV_TIME: 2000,

    ENEMY_FLY: 'fly',
    ENEMY_HORNET: 'hornet',
    ENEMY_FLYING_ANT: 'flyingAnt',
    ENEMY_FLYING_ANT_SOLDIER: 'flyingAntSoldier',

    EFFECT_DAMAGE: 'damage', EFFECT_EXPLOSION: 'explosion',
    LOOT_COIN: 'coin', LOOT_LIFE: 'life',
};
